include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: false
    prefer_const_constructors_in_immutables: false
    prefer_const_literals_to_create_immutables: false
    use_build_context_synchronously: false
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gen.dart"
    - "**/*.config.dart"
    - lib/firebase_options.dart
    - lib/firebase_options_dev.dart
    - lib/firebase_options_stg.dart
  errors:
    invalid_annotation_target: ignore
    one_member_abstracts: ignore
    argument_type_not_assignable: ignore

