name: template
description: A template Flutter Project
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.5

dependencies:
  bloc: ^8.1.0
  change_case: ^1.0.2
  crypto: ^3.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.7
  flutter_screenutil: ^5.5.3+2
  formz: ^0.5.0-dev.1
  google_fonts: ^3.0.1
  intl: ^0.17.0
  rxdart: ^0.27.5
  uuid: ^3.0.6

  # Core
  equatable: ^2.0.5
  dartz: ^0.10.1
  internet_connection_checker_plus: ^1.0.1
  shared_preferences: ^2.0.18
  logging: ^1.1.1

  # Injeção de dependencia
  injectable: ^2.1.0
  get_it: ^7.2.0

  # Rotas
  auto_route: ^6.0.3

  # Estados
  flutter_bloc: ^8.1.2

  # Requisições
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  # - Retrofit
  dio: ^5.0.2
  retrofit: ^4.0.1
  awesome_dio_interceptor: ^1.0.0
  pretty_dio_logger: ^1.3.1

  # Imagem
  flutter_svg: 2.0.3

  # Navegação
  flutter_custom_tabs: ^1.0.4

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.2.0
  injectable_generator: ^2.1.5

  # Testes
  mocktail: ^0.3.0
  bloc_test: ^9.1.1

  # Requisições
  retrofit_generator: ^6.0.0+1

  # Modelos
  json_serializable: ^6.6.1
  freezed: ^2.3.2

  # Rotas
  auto_route_generator: ^6.0.0-rc

  # Icones
  flutter_launcher_icons: "^0.12.0"

dependency_overrides:
  xml: ^6.2.2

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    # flare_flutter: true
    # rive: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/fonts/
    - assets/google_fonts/
    - assets/icons/
    - assets/images/

