name: sme_plateia
description: Aplicativo de eventos de São paulo
version: 1.0.4+3
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  bloc: ^8.1.0
  change_case: ^1.0.2
  crypto: ^3.0.2
  flutter_native_splash: ^2.2.7
  flutter_screenutil: ^5.5.3+2
  formz: ^0.5.0-dev.1
  intl: ^0.18.0
  rxdart: ^0.27.5
  uuid: ^3.0.6

  # Scrool Listagem infinita
  infinite_scroll_pagination: ^3.2.0
  hookified_infinite_scroll_pagination: ^0.1.0
  lazy_load_scrollview: ^1.3.0

  # Hooks
  flutter_hooks: ^0.18.6

  # Fontes
  google_fonts: ^3.0.1

  # Core
  equatable: ^2.0.5
  dartz: ^0.10.1
  internet_connection_checker_plus: ^1.0.1
  shared_preferences: ^2.0.18
  logging: ^1.1.1
  easy_autocomplete: #^1.6.0
    git: https://github.com/SlayerDF/flutter_easy_autocomplete.git
  path_provider: ^2.0.3
  open_file: ^3.0.2

  # Firebase
  firebase_core: ^2.9.0
  firebase_analytics: ^10.1.6
  firebase_crashlytics: ^3.0.17

  # Database
  sqflite: ^2.2.6
  floor: ^1.4.1

  # Injeção de dependencia
  injectable: ^2.1.0
  get_it: ^7.2.0

  # Rotas
  auto_route: ^6.2.0

  # Estados
  flutter_bloc: ^8.1.2

  # Requisições
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  jwt_decode: ^0.3.1
  retrofit: ^4.0.1
  #-Dio
  dio: ^5.0.2
  pretty_dio_logger: ^1.3.1
  fresh_dio: ^0.4.0

  # Imagem
  flutter_svg: 2.0.3
  fast_cached_network_image: ^1.1.1

  # Navegação
  flutter_custom_tabs: ^1.0.4

  # Mapas
  osm_nominatim: ^2.0.1

  flutter_map: ^4.0.0-dev.1
  latlong2: ^0.8.1
  maps_launcher: ^2.2.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.2.0
  injectable_generator: ^2.1.5

  # Testes
  mockito: ^5.3.2
  bloc_test: ^9.1.1

  # Requisições
  retrofit_generator: ^6.0.0+1

  # Modelos
  json_serializable: ^6.6.1
  freezed: ^2.3.2

  # Rotas
  auto_route_generator: ^6.2.0

  # Icones
  flutter_launcher_icons: "^0.12.0"

  # Banco de dados
  floor_generator: ^1.4.1

dependency_overrides:
  xml: ^6.2.2
  intl: ^0.18.0
  dio: ^5.0.2

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    # flare_flutter: true
    # rive: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/fonts/
    - assets/google_fonts/
    - assets/icons/
    - assets/images/
