name: sme_plateia
description: A new Flutter project.
publish_to: 'none' 


version: 1.0.0+1


environment:
  sdk: '>=2.19.3 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Core
  equatable: ^2.0.5
  dartz: ^0.10.1
  internet_connection_checker_plus: ^1.0.1
  shared_preferences: ^2.0.18

  # Injeção de dependencia
  injectable: ^2.1.0
  get_it: ^7.2.0

  # Rotas
  auto_route: ^6.0.0-rc-4

  # Estados
  mobx: ^2.1.4
  flutter_mobx: ^2.0.6+5 
  flutter_triple: ^1.2.8-dev.1
  
  # Requisições
  chopper: ^6.1.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  http: ^0.13.5
  jwt_decode: ^0.3.1
  # - Retrofit
  dio: ^5.0.2
  retrofit: ^4.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  injectable_generator: ^2.1.4
  auto_route_generator: ^6.0.0-rc
  mobx_codegen: ^2.1.1
  chopper_generator: ^6.0.0
  mockito: ^5.3.2
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  retrofit_generator: ^6.0.0+1


flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/logo_saopaulo.png
