name: sme_plateia
description: A new Flutter project.
publish_to: 'none' 


version: 1.0.0+1


environment:
  sdk: '>=2.19.3 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Core
  equatable: ^2.0.5
  dartz: ^0.10.1

  # Injeção de dependencia
  injectable: ^2.1.0
  get_it: ^7.2.0

  # Rotas
  auto_route: ^6.0.0-rc-4

  # Estados
  mobx: ^2.1.4
  flutter_mobx: ^2.0.6+5 
  
  # Requisições
  chopper: ^6.1.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  injectable_generator: ^2.1.4
  auto_route_generator: ^6.0.0-rc
  mobx_codegen: ^2.1.1
  chopper_generator: ^6.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/logo_saopaulo.png
